spring:
  application:
    name: coupon-rush
  datasource:
    url: jdbc:mysql://localhost:13306/coupon_rush?useSSL=false&allowPublicKeyRetrieval=true
    username: coupon
    password: coupon
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  sql:
    init:
      mode: never
  data:
    redis:
      host: localhost
      port: 16379

server:
  port: 8080
  tomcat:
    mbeanregistry:
      enabled: true

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: health,prometheus,info
  metrics:
    tags:
      application: coupon-rush

coupon:
  strategy: pessimistic
  redis-lock:
    wait-time: 5000
    lease-time: 10000
